### ISSUE TITLE
Error reading in CSR graph

### ISSUE THREAD

**Issue by janvekarnaveed** [VHRanger/nodevectors#16]
I am trying to load a 150MB edgelist in csr graph using the command G = cg.read_edgelist("samplelist.edgelist", sep="\t")
But I get the following error:
ValueError                                Traceback (most recent call last)
<ipython-input-4-4de84ac67f80> in <module>
      2 import nodevectors
      3 
----> 4 G = cg.read_edgelist("samplelist.edgelist", sep="\t")

~/anaconda3/envs/python3/lib/python3.6/site-packages/csrgraph/graph.py in read_edgelist(f, sep, header, **readcsvkwargs)
    457             SRC: {elist.src.max()}, {elist.src.min()}
    458             DST: {elist.dst.max()}, {elist.dst.min()}
--> 459         """)
    460     elist.src = elist.src.astype(np.uint32)
    461     elist.dst = elist.dst.astype(np.uint32)

ValueError: 
            Invalid uint32 value in node IDs. Max/min :
            SRC: 8278237827, 15830
            DST: 8237827382738273827382, 2111364

**Comment by VHRanger** [comment]
This is because your node IDs should be factored when they get read into the graph.

Eg. the IDs of the nodes should start at 0 and the maximum node ID should be equal to the number of nodes.

CSRGraphs currently only supports up to 4B nodes (uint32_max) -- anyways that's about as much as you can fit on a single machine. Since you're passing in invalid node IDs here it explodes the logic.

I could fix it when I'm back next week, but in the mean time try factoring your node IDs.

**Comment by janvekarnaveed** [comment]
@VHRanger any update here?

**Comment by VHRanger** [comment]
I'm tracking the changes for this in the CSRGraph repo: https://github.com/VHRanger/CSRGraph/issues/3

I made some changes there which should make it work. Please test that it fixes your problem. If it does, I'll push the fix to the pip version of the CSRGraphs package (and update the dependency on nodevectors afterwards).

I'll close the issue here for now since this is a CSRGraphs issue, not really a nodevectors issue.
