### ISSUE TITLE
Jupyter notebook kernel dies while computing ggvec embeddings

### ISSUE THREAD

**Issue by janvekarnaveed** [VHRanger/nodevectors#17]
I am loading about 7MM edges in a graph object using networkx and then running 
import nodevectors
ggvec_model = nodevectors.GGVec() 
embeddings = ggvec_model.fit_transform(G)

After running for a few minutes jupyter notebook kernel dies. Is there any way forward in this scenario ?

**Comment by VHRanger** [comment]
Hi, Sorry I'll only have time to fix this next week.

0) Try manually making the NX graph into a CSRGraph by making G = cg.csrgraph(G). See if it crashes there.

1) Try running the code in a normal .py file and monitor the RAM usage

2) If the RAM usage is normal try running GGVec for one epoch with the smallest possible settings (embedding dimensions 1 or 2, negative_ratio = 0, etc.)

Please report back what you find

**Comment by janvekarnaveed** [comment]
So the very first step of making a networkx graph object itself fails

**Comment by VHRanger** [comment]
RIght, you're running out of RAM making the networkX object then.

This is because networkX takes a large amount of memory per edge and per node, so trying to make a 7m edge graph on a machine without >1TB of RAM will crash the computer from lack of memory.

Since this particular issue is with networkX I'll close it (The other two are on my side).
