### ISSUE TITLE
Suggestion: support corpus_file parameter

### ISSUE THREAD

**Issue by ubalklen** [VHRanger/nodevectors#18]
Hi.

It would be great if nodevectors could support the word2vec's **corpus_file** parameter that allows for [file-based fast training](https://github.com/RaRe-Technologies/gensim/pull/2127).

What do the devs think about that?

**Comment by VHRanger** [comment]
Thanks! I'll keep the issue open and start working on it when I have some time.

**Comment by VHRanger** [comment]
Hi,

The long term roadmap for this project is to dissociate away from gensim's word2vec implementation.

The plan is to support huge graph file-based fast training through memory-mapped graphs instead of this approach.

I'll close the issue for now, though I'm interested in more suggestions like this, especially if we end up keeping the gensim dependency around
