### ISSUE TITLE
How to increase number of components(features) in output vectors

### ISSUE THREAD

**Issue by janvekarnaveed** [VHRanger/nodevectors#21]
Currently, n_components is set to 32 in all available algorithms like node2vec, GGVec etc. How can I increase to 128? I tried modifying the .py files of these algorithms to increase from 32 to 128. But it did not work. Once I set n_components=128 in .py files and imported package again, running algorithm still outputs vector that has 32 components.

**Comment by VHRanger** [comment]
It's used like any other [SKLearn](https://scikit-learn.org/stable/modules/classes.html) style model.

So you would do something like 

```python
import nodevectors

ggvec = nodevectors.GGVec(
    n_components=128,
    tol_samples=200,
    tol=0.05,
    learning_rate=0.01,
    negative_ratio=0.6,
    max_epoch=6000,
    verbose=True
)
embedding_matrix = ggvec.fit_transform(G)
```

You shouldn't modify the .py files, just change the parameters when creating the model (before fitting or `fit_transforming` it)

Given you're modifying the packages directly, I'd suggest you uninstall and re-install the packages, because they may have been corrupted.
